Test training with an 8-bit bytestring.
This will cause an error in SqlAlchemy in Python 2.7

ProgrammingError: (sqlite3.ProgrammingError) You must not use
8-bit bytestrings unless you use a text_factory that can interpret
8-bit bytestrings (like text_factory = str). It is highly
recommended that you instead just switch your application
to Unicode strings. [SQL: u'SELECT statement.id AS statement_id,
statement.text AS statement_text, statement.extra_data AS
statement_extra_data \nFROM statement \nWHERE statement.text
= ?\n LIMIT ? OFFSET ?']
[parameters: ('\xe4\xbd\xa0\xe5\xa5\xbd\xe5\x90\x97', 1, 0)]